### ISSUE TITLE
Definicion workflow para aplicaciones [iOS]

### ISSUE THREAD

**Issue by blackjid** [platanus/fastlane-cordova#1]
## Problemas
- Mantencion y distribucion de los certificados y perfiles de provisionamiento
- Creacion de las aplicaciones en el store
- Publicacion de las aplicaciones
- Distribucion para testeo de las aplicaciones (testflight)
- Soporte aplicaciones de staging y produccion (conectadas a diferentes servidores)
- Soporte para publicar a una cuenta de cliente
- La convencion debe tener en cuenta los problemas que hemos tenido con el nombre de la aplicacion y cuando se quiere crear la app en la cuenta del cliente. (stages?)
- Como y donde se agregan usuarios para test (internal y external)
- Que cuenta y team se debe usar
- Creacion y configuracion de certificaciones y perfiles para notificaciones push
## Propuesta

Para todo lo que signifique automatizar procesos relacionados con itunesconnect y developer center de apple, usaremos https://github.com/fastlane/fastlane

Estos serian los comando (lanes) que nos debieran permitir relizar todas las acciones

``` shell
## One time commands

# Create the app ID's in the developer console
fastlane ios create 

# Create certificates and provisioning profiles
fastlane ios certs

# Create push certificates, add it to the app id and enable service
fastlane ios services enable:push

## Day-to-day commands
fastlane ios deploy to:appstore env:staging
fastlane ios deploy to:testflight env:production
```
### De la cuenta platanus.

Hay un usuario unico llamado `ios-dev@platan.us` 
### De la cuenta del cliente

Apenas se empiece un desarrollo movil, el cliente **debe** proporcionar una cuenta de desarrollo de apple para publicar en esa cuenta. Sin esto no se pueden hacer publicaciones.

En el caso de applicaciones de platanus, se usa la cuenta de platanus.
### Creacion de las aplicaciones (App ID)

`produce`

Se deben crear dos app ID, en la cuenta del cliente, uno para cada environment (production y staging). Por ejemplo `us.platan.madbill.production` y `us.platan.madbill.staging`. De esta manera se mantienen independiente los releases de staging.
### Build de las aplicaciones

`match, cordova_prepare, recreate_schemes, gym`

wip
### Upload de las aplicaciones

`deliver`

wip
### Testflight

`pilot`

wip
### Profiles and certificates

`match`

Funcionaria en 2 instancias.
1. Al correr el los builds se debe llamar a `match` en modo read-only
2. Crear un lane especifico para crear nuevos certificados y perfiles. `fastlane ios certs` 
### Push Notificationes

`pem, produce`

wip

cc: @platanus/developers plis feedback, todavia estan en processo, pero me vendria muy bien feedback para no caer en alguna trampa.

**Comment by agustinf** [comment]
- la raja 
- probablemente necesitemos el tema push también separado por staging y producción. 
- dice "el cliente debe proporcionar una cuenta de desarrollo de apple ", eso es siempre y cuando el cliente quiera que se publique su app en su cuenta.. verdad? porque varios de nuestros clientes prefieren no pasar por la tortura de hacerse una cuenta developer en Apple.

**Comment by amosrivera** [comment]
Muy bueno! :clap: :clap:. En verdad creo que es un avance importante usar Fastlane sobre el método manual.
- No cache si todas las cosas que están en la lista de "Problemas" se van a atacar con Fastlane. Hay un par de cosas que no creo que sean prioritarias como soportar la cuenta para clientes o como y donde se agregan internal / external testers. No digo que no se implemente, pero dejarlo pero si dejarlo pal final.
- Documentar bien me parece que debería ir en los deseables para que no se vuelva una caja negro(a) (en eso yo podría apoyar los Viernes).

**Comment by blackjid** [comment]
gracias @agustinf y @amosrivera 

> dice "el cliente debe proporcionar una cuenta de desarrollo de apple ", eso es siempre y cuando el cliente quiera que se publique su app en su cuenta.. verdad? porque varios de nuestros clientes prefieren no pasar por la tortura de hacerse una cuenta developer en Apple.

Es realemente una tortura, como para que alguien que quiere sacar una aplicacion no este dispuesto a pasar por eso??? Me imagino que dependiendo si la app es de uso interno o mas consumer, pueden cambiar las ganas de que salga el nombre del cliente en el store, en vez de platanus. Me gusta la idea de tener un par de reglas claras, para simplificar el proceso. Siendo que si hay clientes que van a querer su propia cuenta, seria mas simple solo aceptar eso. (Igual me falta masticarlo un poco mas)

> probablemente necesitemos el tema push también separado por staging y producción.

de acuerdo con el tema push en ambos ambientes

> Documentar bien me parece que debería ir en los deseables para que no se vuelva una caja negro(a) 

de todas maneras, este tema da pa que el generador tenga un buen readme, que esta bien explicado en la guia e incluso un blog post.. Tal vez incluso un video.. :)

> No cache si todas las cosas que están en la lista de "Problemas" se van a atacar con Fastlane. ....

Creo que no..., de hecho le cambie el titulo al issue. La idea es definir todo el flujo y hay cosas que no necesariamente se hacen con fastlane. Pero si me interesa que esten definidas para tener claro el proceso.

> ... Hay un par de cosas que no creo que sean prioritarias como soportar la cuenta para clientes o como y donde se agregan internal / external testers.

Esto tiene que ver con lo que pregunta @agustinf, no lo tengo clarisimo todavia

**Comment by blackjid** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;IV2bYVIF&#x2F;270-es-un-problema-cada-vez-que-queremos-publicar-una-aplicacion-ios-en-el-appstore"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Es un problema cada vez que queremos publicar una aplicacion iOS en el appstore</a>

**Comment by blackjid** [comment]
voy a cerrar este issue como terminado.... hay tres puntos que no estar listos, pero no tienen que ver con codigo sino con practicas....

creo que trello es mejor para ver eso

**Comment by blackjid** [comment]
released with the merge of #2
