### ISSUE TITLE
more details about `cordova prepare --env=`

### ISSUE THREAD

**Issue by AilisObrian** [platanus/fastlane-cordova#8]
Hello, Thanks for this great repository!

When I looked around build lane, I saw `cordova prepare --env=`.
`--env=` would be send to `before_prepare` by `CORDOVA_CMDLINE`

So I want to know some sample of your `before_prepare` hook.

Thanks always!

**Comment by AilisObrian** [comment]
@minhoryang

**Comment by blackjid** [comment]
Hey... 

this is the super simple `before_prepare` we are using.
https://github.com/platanus/generator-platanus-ionic/blob/master/app/templates/base/hooks/before_prepare/build_www.js

We use that to trigger a gulp build which set up an angular constant through a gulp task...
https://github.com/platanus/generator-platanus-ionic/blob/master/app/templates/base/gulpfile.js#L14-L15

I hope that helps...

**Comment by minhoryang** [comment]
Oops, I wasn't noticed that was opened. Thanks!!!!
