### ISSUE TITLE
Invalid request body

### ISSUE THREAD

**Issue by raphaelgodoi** [platanus/fastlane-cordova#9]
Hi,

i'm getting this error when try to deploy to testflight 

![captura de tela 2016-04-29 as 11 53 30](https://cloud.githubusercontent.com/assets/3275387/14919842/06c28984-0e01-11e6-9da1-580750e4c0c2.png)

**Comment by blackjid** [comment]
Did you set the team_id in the `fastlane/config.yml` file?

**Comment by raphaelgodoi** [comment]
Yeah, I'ts fixed now..

I was using the team_id that is showing on itunes connect.

**Comment by blackjid** [comment]
Ok, great. I'm going to close the issue. :)
